# Generated by Django 3.2.4 on 2022-01-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('industory', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
            ],
        ),
    ]
