# Generated by Django 3.2.4 on 2022-01-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokopade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
