# Generated by Django 3.2.4 on 2022-01-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_employee_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='Point',
        ),
        migrations.RemoveField(
            model_name='player',
            name='Ranking',
        ),
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ranking',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tokopade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Players', to='first_app.tokopade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokopade',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tokopade',
            name='number',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
