# Generated by Django 3.2.4 on 2022-01-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20220113_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokopade',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
