# Generated by Django 3.2.4 on 2022-09-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_tokopade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokopade',
            name='tournament',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tokopade',
            name='number',
            field=models.IntegerField(max_length=256, null=True),
        ),
    ]
